CREATE TABLE DBO.BREAKFAST (
	[id]           INT          IDENTITY (1, 1) NOT NULL,
	[name]		   VARCHAR(50)  NOT NULL,
	[ingr1_name]   VARCHAR(40)	NOT NULL,
	[ingr1_carbs]  float	NOT NULL,
	[ingr1_prot]  float	NOT NULL,
	[ingr1_fats]  float	NOT NULL,
	[ingr1_typSize]  float	NOT NULL,
	[ingr1_kCalTotal]  float	NOT NULL,
	[ingr2_name]   VARCHAR(40)	NOT NULL,
	[ingr2_carbs]  float	NOT NULL,
	[ingr2_prot]  float	NOT NULL,
	[ingr2_fats]  float	NOT NULL,
	[ingr2_typSize]  float	NOT NULL,
	[ingr2_kCalTotal]  float	NOT NULL,
	[ingr3_name]   VARCHAR(40)	NOT NULL,
	[ingr3_carbs]  float	NOT NULL,
	[ingr3_prot]  float	NOT NULL,
	[ingr3_fats]  float	NOT NULL,
	[ingr3_typSize]  float	NOT NULL,
	[ingr3_kCalTotal]  float	NOT NULL,
	[ingr4_name]   VARCHAR(40)	NULL,
	[ingr4_carbs]  float	NULL,
	[ingr4_prot]  float	NULL,
	[ingr4_fats]  float	NULL,
	[ingr4_typSize]  float	NULL,
	[ingr4_kCalTotal]  float	NULL,
	[ingr5_name]   VARCHAR(40) NULL,
	[ingr5_carbs]  float NULL,
	[ingr5_prot]  float	NULL,
	[ingr5_fats]  float	NULL,
	[ingr5_typSize]  float	NULL,
	[ingr5_kCalTotal]  float	NULL,
	[ingr6_name]   VARCHAR(40)	NULL,
	[ingr6_carbs]  float	NULL,
	[ingr6_prot]  float	NULL,
	[ingr6_fats]  float	NULL,
	[ingr6_typSize]  float	NULL,
	[ingr6_kCalTotal]  float	NULL,
	[ingr7_name]   VARCHAR(40)	NULL,
	[ingr7_carbs]  float	NULL,
	[ingr7_prot]  float	NULL,
	[ingr7_fats]  float NULL,
	[ingr7_typSize]  float	NULL,
	[ingr7_kCalTotal]  float	NULL,
	[ingr8_name]   VARCHAR(40)	NULL,
	[ingr8_carbs]  float	NULL,
	[ingr8_prot]  float	NULL,
	[ingr8_fats]  float	NULL,
	[ingr8_typSize]  float	NULL,
	[ingr8_kCalTotal]  float	NULL,
	[ingr9_name]   VARCHAR(40)	NULL,
	[ingr9_carbs]  float	NULL,
	[ingr9_prot]  float	NULL,
	[ingr9_fats]  float	NULL,
	[ingr9_typSize]  float	NULL,
	[ingr9_kCalTotal]  float	NULL,
	[carbsTot] AS (ingr1_carbs+ingr2_carbs+ingr3_carbs+ingr4_carbs+ingr5_carbs+ingr6_carbs+ingr7_carbs+ingr8_carbs+ingr9_carbs) PERSISTED,
	[protTot] AS (ingr1_prot+ingr2_prot+ingr3_prot+ingr4_prot+ingr5_prot+ingr6_prot+ingr7_prot+ingr8_prot+ingr9_prot) PERSISTED,
	[fatsTot] AS (ingr1_fats+ingr2_fats+ingr3_fats+ingr4_fats+ingr5_fats+ingr6_fats+ingr7_fats+ingr8_fats+ingr9_fats) PERSISTED,
	[typSizeTot] AS (ingr1_typSize+ingr2_typSize+ingr3_typSize+ingr4_typSize+ingr5_typSize+ingr6_typSize+ingr7_typSize+ingr8_typSize+ingr9_typSize) PERSISTED,
	[kCalTot] AS (ingr1_kCalTotal+ingr2_kCalTotal+ingr3_kCalTotal+ingr4_kCalTotal+ingr5_kCalTotal+ingr6_kCalTotal+ingr7_kCalTotal+ingr8_kCalTotal+ingr9_kCalTotal) PERSISTED,
	[carbsTot_perc] AS ((carbsTot/typSizeTot)*100) PERSISTED,
	[protTot_perc] AS ((protTot/typSizeTot)*100) PERSISTED,
	[fatsTot_perc] AS ((fatsTot/typSizeTot)*100) PERSISTED
);

CREATE TABLE DBO.MEALS (
	[id]           INT          IDENTITY (1, 1) NOT NULL,
	[name]		   VARCHAR(50)  NOT NULL,
	[ingr1_name]   VARCHAR(40)	NOT NULL,
	[ingr1_carbs]  float	NOT NULL,
	[ingr1_prot]  float	NOT NULL,
	[ingr1_fats]  float	NOT NULL,
	[ingr1_typSize]  float	NOT NULL,
	[ingr1_kCalTotal]  float	NOT NULL,
	[ingr2_name]   VARCHAR(40)	NOT NULL,
	[ingr2_carbs]  float	NOT NULL,
	[ingr2_prot]  float	NOT NULL,
	[ingr2_fats]  float	NOT NULL,
	[ingr2_typSize]  float	NOT NULL,
	[ingr2_kCalTotal]  float	NOT NULL,
	[ingr3_name]   VARCHAR(40)	NOT NULL,
	[ingr3_carbs]  float	NOT NULL,
	[ingr3_prot]  float	NOT NULL,
	[ingr3_fats]  float	NOT NULL,
	[ingr3_typSize]  float	NOT NULL,
	[ingr3_kCalTotal]  float	NOT NULL,
	[ingr4_name]   VARCHAR(40)	NULL,
	[ingr4_carbs]  float	NULL,
	[ingr4_prot]  float	NULL,
	[ingr4_fats]  float	NULL,
	[ingr4_typSize]  float	NULL,
	[ingr4_kCalTotal]  float	NULL,
	[ingr5_name]   VARCHAR(40) NULL,
	[ingr5_carbs]  float NULL,
	[ingr5_prot]  float	NULL,
	[ingr5_fats]  float	NULL,
	[ingr5_typSize]  float	NULL,
	[ingr5_kCalTotal]  float	NULL,
	[ingr6_name]   VARCHAR(40)	NULL,
	[ingr6_carbs]  float	NULL,
	[ingr6_prot]  float	NULL,
	[ingr6_fats]  float	NULL,
	[ingr6_typSize]  float	NULL,
	[ingr6_kCalTotal]  float	NULL,
	[ingr7_name]   VARCHAR(40)	NULL,
	[ingr7_carbs]  float	NULL,
	[ingr7_prot]  float	NULL,
	[ingr7_fats]  float NULL,
	[ingr7_typSize]  float	NULL,
	[ingr7_kCalTotal]  float	NULL,
	[ingr8_name]   VARCHAR(40)	NULL,
	[ingr8_carbs]  float	NULL,
	[ingr8_prot]  float	NULL,
	[ingr8_fats]  float	NULL,
	[ingr8_typSize]  float	NULL,
	[ingr8_kCalTotal]  float	NULL,
	[ingr9_name]   VARCHAR(40)	NULL,
	[ingr9_carbs]  float	NULL,
	[ingr9_prot]  float	NULL,
	[ingr9_fats]  float	NULL,
	[ingr9_typSize]  float	NULL,
	[ingr9_kCalTotal]  float	NULL,
	[carbsTot] AS (ingr1_carbs+ingr2_carbs+ingr3_carbs+ingr4_carbs+ingr5_carbs+ingr6_carbs+ingr7_carbs+ingr8_carbs+ingr9_carbs) PERSISTED,
	[protTot] AS (ingr1_prot+ingr2_prot+ingr3_prot+ingr4_prot+ingr5_prot+ingr6_prot+ingr7_prot+ingr8_prot+ingr9_prot) PERSISTED,
	[fatsTot] AS (ingr1_fats+ingr2_fats+ingr3_fats+ingr4_fats+ingr5_fats+ingr6_fats+ingr7_fats+ingr8_fats+ingr9_fats) PERSISTED,
	[typSizeTot] AS (ingr1_typSize+ingr2_typSize+ingr3_typSize+ingr4_typSize+ingr5_typSize+ingr6_typSize+ingr7_typSize+ingr8_typSize+ingr9_typSize) PERSISTED,
	[kCalTot] AS (ingr1_kCalTotal+ingr2_kCalTotal+ingr3_kCalTotal+ingr4_kCalTotal+ingr5_kCalTotal+ingr6_kCalTotal+ingr7_kCalTotal+ingr8_kCalTotal+ingr9_kCalTotal) PERSISTED,
	[carbsTot_perc] AS ((carbsTot/typSizeTot)*100) PERSISTED,
	[protTot_perc] AS ((protTot/typSizeTot)*100) PERSISTED,
	[fatsTot_perc] AS ((fatsTot/typSizeTot)*100) PERSISTED
);

CREATE TABLE DBO.DINNER (
	[id]           INT          IDENTITY (1, 1) NOT NULL,
	[name]		   VARCHAR(50)  NOT NULL,
	[ingr1_name]   VARCHAR(40)	NOT NULL,
	[ingr1_carbs]  float	NOT NULL,
	[ingr1_prot]  float	NOT NULL,
	[ingr1_fats]  float	NOT NULL,
	[ingr1_typSize]  float	NOT NULL,
	[ingr1_kCalTotal]  float	NOT NULL,
	[ingr2_name]   VARCHAR(40)	NOT NULL,
	[ingr2_carbs]  float	NOT NULL,
	[ingr2_prot]  float	NOT NULL,
	[ingr2_fats]  float	NOT NULL,
	[ingr2_typSize]  float	NOT NULL,
	[ingr2_kCalTotal]  float	NOT NULL,
	[ingr3_name]   VARCHAR(40)	NOT NULL,
	[ingr3_carbs]  float	NOT NULL,
	[ingr3_prot]  float	NOT NULL,
	[ingr3_fats]  float	NOT NULL,
	[ingr3_typSize]  float	NOT NULL,
	[ingr3_kCalTotal]  float	NOT NULL,
	[ingr4_name]   VARCHAR(40)	NULL,
	[ingr4_carbs]  float	NULL,
	[ingr4_prot]  float	NULL,
	[ingr4_fats]  float	NULL,
	[ingr4_typSize]  float	NULL,
	[ingr4_kCalTotal]  float	NULL,
	[ingr5_name]   VARCHAR(40) NULL,
	[ingr5_carbs]  float NULL,
	[ingr5_prot]  float	NULL,
	[ingr5_fats]  float	NULL,
	[ingr5_typSize]  float	NULL,
	[ingr5_kCalTotal]  float	NULL,
	[ingr6_name]   VARCHAR(40)	NULL,
	[ingr6_carbs]  float	NULL,
	[ingr6_prot]  float	NULL,
	[ingr6_fats]  float	NULL,
	[ingr6_typSize]  float	NULL,
	[ingr6_kCalTotal]  float	NULL,
	[ingr7_name]   VARCHAR(40)	NULL,
	[ingr7_carbs]  float	NULL,
	[ingr7_prot]  float	NULL,
	[ingr7_fats]  float NULL,
	[ingr7_typSize]  float	NULL,
	[ingr7_kCalTotal]  float	NULL,
	[ingr8_name]   VARCHAR(40)	NULL,
	[ingr8_carbs]  float	NULL,
	[ingr8_prot]  float	NULL,
	[ingr8_fats]  float	NULL,
	[ingr8_typSize]  float	NULL,
	[ingr8_kCalTotal]  float	NULL,
	[ingr9_name]   VARCHAR(40)	NULL,
	[ingr9_carbs]  float	NULL,
	[ingr9_prot]  float	NULL,
	[ingr9_fats]  float	NULL,
	[ingr9_typSize]  float	NULL,
	[ingr9_kCalTotal]  float	NULL,
	[carbsTot] AS (ingr1_carbs+ingr2_carbs+ingr3_carbs+ingr4_carbs+ingr5_carbs+ingr6_carbs+ingr7_carbs+ingr8_carbs+ingr9_carbs) PERSISTED,
	[protTot] AS (ingr1_prot+ingr2_prot+ingr3_prot+ingr4_prot+ingr5_prot+ingr6_prot+ingr7_prot+ingr8_prot+ingr9_prot) PERSISTED,
	[fatsTot] AS (ingr1_fats+ingr2_fats+ingr3_fats+ingr4_fats+ingr5_fats+ingr6_fats+ingr7_fats+ingr8_fats+ingr9_fats) PERSISTED,
	[typSizeTot] AS (ingr1_typSize+ingr2_typSize+ingr3_typSize+ingr4_typSize+ingr5_typSize+ingr6_typSize+ingr7_typSize+ingr8_typSize+ingr9_typSize) PERSISTED,
	[kCalTot] AS (ingr1_kCalTotal+ingr2_kCalTotal+ingr3_kCalTotal+ingr4_kCalTotal+ingr5_kCalTotal+ingr6_kCalTotal+ingr7_kCalTotal+ingr8_kCalTotal+ingr9_kCalTotal) PERSISTED,
	[carbsTot_perc] AS ((carbsTot/typSizeTot)*100) PERSISTED,
	[protTot_perc] AS ((protTot/typSizeTot)*100) PERSISTED,
	[fatsTot_perc] AS ((fatsTot/typSizeTot)*100) PERSISTED
);