import type { Metadata } from "next";
import "@styles/fonts.css";
import "@styles/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import {routing} from 'i18n/routing';
import { styleText } from "util";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const messagesModule = await getMessages({ locale });

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body
        className="poppins-400-regular antialeased"
      >
        <NextIntlClientProvider messages={messagesModule}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}